"""add audit_logs and config_revisions

Revision ID: 13248e4615f1
Revises: 
Create Date: 2026-08-13 10:32:19.323600
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13248e4615f1'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=True),
    sa.Column('diff', sa.JSON(), nullable=True),
    sa.Column('target', sa.String(length=512), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('audit_id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_at'), ['at'], unique=False)

    op.create_table('config_revisions',
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=256), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('revision')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('config_revisions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_at'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
